### ISSUE TITLE
Web server and database server

### ISSUE THREAD

**Issue by alejosv** [wavedrift/docker-conquest#1]
The server conquest enable a web interface, in the dockerfile, line 50, is given by laying Apache is installed, should not the dockerfile also install Apache?

I also consider the database, it would be interesting to have a dockerfile that support different database engines, it would be practical.

**Comment by wavedrift** [comment]
Hi alejosv,

Thanks for the feedback.  Sorry for the late reply - I was away on holiday last week with little internet access.  

Apache is installed in the Dockerfile in line 25.  I believe this is what you mean?

Agreed about the database engines.  I will look into this and keep this issue open in the meantime.  It would make sense to support all of the database types supported by ConQuest.

**Comment by alejosv** [comment]
Thanks Wavedrift for your reply

I think it might initially consider MySql and Postgresql after, this will help a lot.
